import type { Metadata } from "next";
import { Geist, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";
import ViewportContainer from "../components/ViewPortContainer";
import ScalableContent from "../components/ScalableContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${bebasNeue.variable} antialiased bg-[url('/mainbg.png')] bg-cover bg-center bg-no-repeat`}
      >
        <ViewportContainer>
          <ScalableContent>
            <Navigation />
            {children}
          </ScalableContent>
        </ViewportContainer>
      </body>
    </html>
  );
}
